class Constants
  SAVE_COMPONENT_IMAGES = false

  SHADOW_OFFSET = 15

  IMAGE_WIDTH = 1300
  IMAGE_HEIGHT = 1300

  WILDNESS_FACTOR = 30.0
  WILDNESS_MIN = 40.0

  SPLAT_WILDNESS_FACTOR = 0.2
  SPLAT_WILDNESS_MIN = 2.0

  CIRCLE_WILDNESS_FACTOR = 15.0
  CIRCLE_WILDNESS_MIN = 25.0

  WATERCOLOR_X_MIN = -100
  WATERCOLOR_X_MAX = IMAGE_WIDTH + 100
  WATERCOLOR_Y_MIN = -100
  WATERCOLOR_Y_MAX = IMAGE_HEIGHT + 100
  WATERCOLOR_STRIPE_COUNT = 3
  WATERCOLOR_STRIPE_OVERLAP = 100

  WATERCOLOR_INITIAL_DEFORMATIONS = 6
  WATERCOLOR_SPLAT_INITIAL_DEFORMATIONS = 3
  WATERCOLOR_SLICE_COUNT = 75
  WATERCOLOR_SPLAT_SLICE_COUNT = 5
  WATERCOLOR_SLICE_DEFORMATIONS = 2
  WATERCOLOR_SPLAT_SLICE_DEFORMATIONS = 4
  WATERCOLOR_SLICE_OPACITY = 0.08
  WATERCOLOR_STROKE_OPACITY = 0.45
  WATERCOLOR_STROKE_WIDTH = 1.0
  WATERCOLOR_SPLAT_FILL_OPACITY = 0.12

  WATERCOLOR_MIN_CIRCLES = 10
  WATERCOLOR_MAX_CIRCLES = 20
  WATERCOLOR_MIN_CIRCLE_RADIUS = 50
  WATERCOLOR_MAX_CIRCLE_RADIUS = 80

  WATERCOLOR_MIN_SPLATS = 30
  WATERCOLOR_MAX_SPLATS = 60
  WATERCOLOR_MIN_SPLAT_RADIUS = 10
  WATERCOLOR_MAX_SPLAT_RADIUS = 20

  MIN_LEAVES = 25
  MAX_LEAVES = 45
  LEAF_MIN_ANGLE_DISTANCE = 0.0
  LEAF_GAP_MIN_ANGLE = 5.0
  LEAF_GAP_MAX_ANGLE = 60.0
  LEAF_MIN_GAPS = 1
  LEAF_MAX_GAPS = 3

  MIN_GLOBAL_SCALE = 0.3
  MAX_GLOBAL_SCALE = 1.2
end
